### ISSUE TITLE
Issue on Bullseye OS

### ISSUE THREAD

**Issue by SimpleSon** [danb35/raspi-ups-stats#2]
Updated to the latest Raspberry Pi OS with Bullseye and now I am getting the following error when running the script.  I have one of the original versions of this script on my prior build before your fork of that project, which works, but would eventually error out.  I copied it over to this new Bullseye build and at immediately throws the same error as my fresh script.  
![RuntimeError](https://user-images.githubusercontent.com/56879459/141408996-5b6e61c8-3140-4a1f-a6ac-82e8f6c3a8cc.png)

**Comment by peter-nufc** [comment]
Unfortunately I'm have the exact same issue after upgrading to Bullseye.

**Comment by SimpleSon** [comment]
I have fallen back to just using the stats display without the UPS info.  I can get that to run properly based on the original work of @mklements, but as he suggested, I don't know that the UPS is ready for Bullseye.

**Comment by BlackNet** [comment]
I was able to change a few things and get it working with bullseye, with charge/discharge/voltage/etc...

**Comment by BlackNet** [comment]
Here is my working code, including charging/discharging/voltage/etc for this project under 11.1, Raspbian Bullseye.

https://street-tek.dev/stats.py

**Comment by alanManster** [comment]
> Here is my working code, including charging/discharging/voltage/etc for this project under 11.1, Raspbian Bullseye.
> 
> https://street-tek.dev/stats.py

excuse me kind sir, after trying to apply your code to my system I appear to be running the script for a little while(varies from 1 min to 10 mins) then I get an error:

aReceiveBuf = bus.read_i2c_block_data(DEVICE_ADDR, 0, 32)
ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error

I am able to start it up again, and it will run for a little while (again from 1-10 minutes) then it will give that error. any tips or information about fixing this issue?

**Comment by BlackNet** [comment]
> > Here is my working code, including charging/discharging/voltage/etc for this project under 11.1, Raspbian Bullseye.
> 
> > 
> 
> > https://street-tek.dev/stats.py
> 
> 
> 
> excuse me kind sir, after trying to apply your code to my system I appear to be running the script for a little while(varies from 1 min to 10 mins) then I get an error:
> 
> 
> 
> aReceiveBuf = bus.read_i2c_block_data(DEVICE_ADDR, 0, 32)
> 
> ioctl(self.fd, I2C_SMBUS, msg)
> 
> OSError: [Errno 121] Remote I/O error
> 
> 
> 
> I am able to start it up again, and it will run for a little while (again from 1-10 minutes) then it will give that error. any tips or information about fixing this issue?



Look in syslog, message, daemon, or kern and see what shows there it should show errors and warning related to the device and give much more details. It could be as simple as a loose connection.

**Comment by Stan4oe** [comment]
> Here is my working code, including charging/discharging/voltage/etc for this project under 11.1, Raspbian Bullseye.
> 
> https://street-tek.dev/stats.py

HI, can you post the code here it seams, I don't have authorisation to download it. Thank you.

**Comment by BlackNet** [comment]
> > Here is my working code, including charging/discharging/voltage/etc for this project under 11.1, Raspbian Bullseye.
> > https://street-tek.dev/stats.py
> 
> HI, can you post the code here it seams, I don't have authorisation to download it. Thank you.

Woops, I moved that to a closed system and forgot about a few links.

Code did not seem to format correctly.  I attached as a txt file, just rename it to code.py (py files are not allowed for some reason)

[stats.py.txt](https://github.com/danb35/raspi-ups-stats/files/12706436/stats.py.txt)

**Comment by Stan4oe** [comment]
Thank you for the script, but still has some issues, probably some dependencies. Installed Ina-219, but for some reason the script cant-find it (I'm so new in this!).  Can you help me. Thank you.   
![prsc02](https://github.com/danb35/raspi-ups-stats/assets/145845755/74d9121d-70d4-41fd-bd59-c37f499b850f)

Traceback (most recent call last):
  File "/home/PIpc/Downloads/stats.py", line 105, in <module>
    ina.configure()
  File "/home/PIpc/.local/lib/python3.9/site-packages/ina219.py", line 173, in configure
    self._calibrate(
  File "/home/PIpc/.local/lib/python3.9/site-packages/ina219.py", line 310, in _calibrate
    self._calibration_register(calibration)
  File "/home/PIpc/.local/lib/python3.9/site-packages/ina219.py", line 356, in _calibration_register
    self.__write_register(self.__REG_CALIBRATION, register_value)
  File "/home/PIpc/.local/lib/python3.9/site-packages/ina219.py", line 388, in __write_register
    self._i2c.writeList(register, register_bytes)
  File "/home/PIpc/.local/lib/python3.9/site-packages/Adafruit_GPIO/I2C.py", line 127, in writeList
    self._bus.write_i2c_block_data(self._address, register, data)
  File "/home/PIpc/.local/lib/python3.9/site-packages/Adafruit_PureIO/smbus.py", line 357, in write_i2c_block_data
    self._device.write(data)
OSError: [Errno 121] Remote I/O error

**Comment by BlackNet** [comment]
That needs to be run on the pi itself, so ssh in and run from there.

**Comment by Stan4oe** [comment]
It is run on the pi itself. The print screen is from the monitor hock it to the pi. I try from the comand prom - same answer. Probably is somthing small but I luck of experiance.
